-- TALON: application user authentication fields for MySQL 8.0.
-- Apply after migrations 001 through 005. This migration does not create a
-- default account: deployment credentials must be provisioned by the backend.
-- Store an Argon2id or bcrypt hash generated by the backend, never plaintext.
SET time_zone = '+00:00';

ALTER TABLE users
  ADD COLUMN email VARCHAR(254) NULL AFTER external_subject,
  ADD COLUMN password_hash VARCHAR(255) NULL AFTER email,
  ADD COLUMN force_password_change BOOLEAN NOT NULL DEFAULT TRUE AFTER password_hash,
  ADD COLUMN mfa_required BOOLEAN NOT NULL DEFAULT FALSE AFTER force_password_change,
  ADD COLUMN session_timeout_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 60 AFTER mfa_required,
  ADD COLUMN password_changed_at DATETIME(6) NULL AFTER session_timeout_minutes,
  ADD CONSTRAINT chk_user_session_timeout CHECK (session_timeout_minutes BETWEEN 5 AND 480),
  ADD UNIQUE KEY uq_users_org_email (organization_id, email);
